#!/bin/bash

# Copyright (C) 2014 Amazon.com, Inc. or its affiliates.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#    http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the
# License.

if [ "$#" -ne 1 ] ; then
  echo "$0 <device path>" >&2
  exit 1
fi

grep -qE '\bmaxcpus=' /proc/cmdline
if [ "$?" -ne 1 ]; then
  echo "maxcpus set, not bringing up additional cpus" >&2
  exit 2
fi

if [ ! -e /sys$1/online ]; then
  echo "/sys$1/online does not exist" >&2
  exit 3
fi

echo 1 > /sys$1/online
